# Generated by Django 6.0.3 on 2026-04-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caminhoneiro',
            name='e_diamante',
        ),
        migrations.RemoveField(
            model_name='caminhoneiro',
            name='pontuacao_experiencia',
        ),
        migrations.AddField(
            model_name='caminhoneiro',
            name='media_notas',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='media_avaliacao',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
