# Generated by Django 6.0.3 on 2026-04-29 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_caminhoneiro_e_diamante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caminhoneiro',
            name='e_diamante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nota_corte_padrao',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
