# Generated by Django 6.0.3 on 2026-04-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('distancia_km', models.FloatField()),
                ('valor_bruto_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimativa_pedagio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comissao_app', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_transito', 'Em Trânsito'), ('finalizado', 'Finalizado')], default='disponivel', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_postadas', to='usuario.empresa')),
                ('motorista_alocado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.caminhoneiro')),
            ],
        ),
    ]
