# Generated by Django 6.0.3 on 2026-04-29 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='consumo_veiculo_alocado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carga',
            name='nota_minima_motorista',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
