# Generated by Django 6.0.3 on 2026-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0002_carga_consumo_veiculo_alocado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='comissao_app',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
