# Generated by Django 6.0.3 on 2026-04-27 22:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('tempo_espera_carregamento', models.DurationField(help_text='Quanto tempo demorou para carregar?')),
                ('tem_banheiro_limpo', models.BooleanField(default=True)),
                ('local_seguro', models.BooleanField(default=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('caminhoneiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.caminhoneiro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='usuario.empresa')),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
