# Generated by Django 6.0.3 on 2026-04-27 23:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('usuario', '0002_remove_caminhoneiro_e_diamante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCaminhoneiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('entrega_no_prazo', models.BooleanField(default=True)),
                ('cuidado_com_carga', models.BooleanField(default=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('caminhoneiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_recebidas', to='usuario.caminhoneiro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.empresa')),
            ],
            options={
                'verbose_name_plural': 'Avaliações de Motoristas',
            },
        ),
    ]
